# Generated by Django 6.0.6 on 2026-06-28 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0002_group_monitortarget_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitortarget",
            name="check_interval",
            field=models.IntegerField(
                choices=[
                    (1, "A cada 1 minuto"),
                    (5, "A cada 5 minutos"),
                    (15, "A cada 15 minutos"),
                    (30, "A cada 30 minutos"),
                    (48, "A cada 48 minutos (30 vezes por dia)"),
                    (60, "A cada 1 hora"),
                    (120, "A cada 2 horas"),
                    (360, "A cada 6 horas"),
                    (720, "A cada 12 horas"),
                    (1440, "A cada 24 horas (1 vez por dia)"),
                ],
                default=60,
                help_text="Frequência de verificação deste sensor (em minutos)",
            ),
        ),
    ]
