# Generated by Django 6.0.6 on 2026-06-28 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_monitortarget_telegram_alert_threshold'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='Ação executada (ex: Criar, Editar, Excluir, Ativar, Desativar, Lote)', max_length=50)),
                ('model_name', models.CharField(help_text='Modelo modificado (ex: Dispositivo, Grupo)', max_length=100)),
                ('object_repr', models.CharField(help_text='Representação do objeto (ex: Câmera Portão - 45.174.193.10:40001)', max_length=255)),
                ('changes', models.TextField(blank=True, help_text='Descrição amigável das alterações efetuadas', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('availability', models.FloatField(help_text='Porcentagem de disponibilidade diária (0 a 100)')),
                ('avg_latency', models.FloatField(help_text='Latência média em milissegundos')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to='monitor.monitortarget')),
            ],
            options={
                'ordering': ['-date', 'target'],
                'unique_together': {('target', 'date')},
            },
        ),
    ]
