# Generated by Django 6.0.6 on 2026-06-28 06:49

from django.db import migrations
from django.db.models import Avg
from django.utils import timezone
from datetime import datetime, timedelta

def populate_daily_summaries(apps, schema_editor):
    MonitorTarget = apps.get_model('monitor', 'MonitorTarget')
    MonitorLog = apps.get_model('monitor', 'MonitorLog')
    DailySummary = apps.get_model('monitor', 'DailySummary')

    # Get the oldest log timestamp
    oldest_log = MonitorLog.objects.order_by('timestamp').first()
    if not oldest_log:
        return  # No logs to consolidate

    # Start date is the date of the oldest log (local time date)
    start_date = timezone.localtime(oldest_log.timestamp).date()
    # End date is yesterday
    end_date = timezone.localdate() - timedelta(days=1)

    if start_date > end_date:
        return

    current_date = start_date
    while current_date <= end_date:
        # Define the timezone-aware range for the current_date
        day_start = timezone.make_aware(datetime.combine(current_date, datetime.min.time()))
        day_end = timezone.make_aware(datetime.combine(current_date, datetime.max.time()))

        targets = MonitorTarget.objects.all()
        for target in targets:
            # Query logs for this target on this day
            logs = MonitorLog.objects.filter(target=target, timestamp__range=(day_start, day_end))
            total_count = logs.count()

            if total_count == 0:
                continue  # Skip targets with no logs on this day

            success_count = logs.filter(status=True).count()
            availability = round(success_count * 100.0 / total_count, 1)
            
            # Calculate average latency
            avg_lat = logs.aggregate(Avg('latency'))['latency__avg'] or 0.0
            avg_lat = round(avg_lat, 2)

            DailySummary.objects.update_or_create(
                target=target,
                date=current_date,
                defaults={
                    'availability': availability,
                    'avg_latency': avg_lat
                }
            )

        current_date += timedelta(days=1)


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_auditlog_dailysummary'),
    ]

    operations = [
        migrations.RunPython(populate_daily_summaries, migrations.RunPython.noop),
    ]
