# Generated by Django 6.0.6 on 2026-06-29 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0007_retroactive_daily_summaries"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="monitortarget",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="monitortarget",
            name="last_counter_time",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp do último valor bruto (para tráfego)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="monitortarget",
            name="last_counter_val",
            field=models.BigIntegerField(
                blank=True,
                help_text="Último valor bruto de bytes (para tráfego)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="monitortarget",
            name="sensor_identifier",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Identificador único do sensor (ex: OID ou nome da interface)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="monitortarget",
            name="sensor_type",
            field=models.CharField(
                choices=[
                    ("tcp", "Porta TCP"),
                    ("ping", "Ping (ICMP)"),
                    ("snmp_traffic", "Tráfego SNMP"),
                    ("snmp_numeric", "Valor Numérico SNMP"),
                    ("mikrotik_api", "MikroTik API"),
                ],
                default="tcp",
                help_text="Tipo de monitoramento/coleta",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="monitortarget",
            name="sensor_value",
            field=models.CharField(
                blank=True,
                help_text="Valor formatado da última coleta",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="monitortarget",
            name="port",
            field=models.IntegerField(
                blank=True,
                help_text="Porta TCP (ex: 8080) - Opcional para sensores não-TCP",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nome amigável do equipamento (ex: OLT Parks, MikroTik BGP)",
                        max_length=255,
                    ),
                ),
                (
                    "host",
                    models.CharField(
                        help_text="Endereço IP ou Hostname (ex: 172.31.255.2)",
                        max_length=255,
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("mikrotik", "MikroTik RouterOS"),
                            ("parks_olt", "OLT Parks GPON"),
                            ("generic_snmp", "Genérico (SNMP)"),
                            ("generic_ping", "Genérico (Apenas Ping)"),
                        ],
                        default="generic_ping",
                        help_text="Tipo de equipamento para comunicação e coleta de dados",
                        max_length=50,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Habilitar/Desabilitar monitoramento de todos os sensores deste dispositivo",
                    ),
                ),
                (
                    "snmp_community",
                    models.CharField(
                        default="public",
                        help_text="Comunidade SNMP v2c (ex: public)",
                        max_length=255,
                    ),
                ),
                (
                    "snmp_port",
                    models.IntegerField(
                        default=161, help_text="Porta SNMP (padrão: 161)"
                    ),
                ),
                (
                    "api_username",
                    models.CharField(
                        blank=True,
                        help_text="Usuário da API MikroTik (opcional)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "api_password",
                    models.CharField(
                        blank=True,
                        help_text="Senha da API MikroTik (opcional)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "api_port",
                    models.IntegerField(
                        default=8728, help_text="Porta da API MikroTik (padrão: 8728)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        help_text="Grupo ao qual este equipamento pertence",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="devices",
                        to="monitor.group",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="monitortarget",
            name="device",
            field=models.ForeignKey(
                blank=True,
                help_text="Dispositivo ao qual este sensor pertence",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sensors",
                to="monitor.device",
            ),
        ),
    ]
