# Generated by Django 6.0.6 on 2026-06-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0008_alter_monitortarget_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('mikrotik', 'MikroTik RouterOS (API)'), ('mikrotik_snmp', 'MikroTik (SNMP)'), ('parks_olt', 'OLT Parks GPON'), ('generic_snmp', 'Genérico (SNMP)'), ('generic_ping', 'Genérico (Apenas Ping)')], default='generic_ping', help_text='Tipo de equipamento para comunicação e coleta de dados', max_length=50),
        ),
    ]
