# Generated by Django 6.0.6 on 2026-06-30 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0012_alter_monitortarget_telegram_alert_threshold"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="monitortarget",
            options={"ordering": ["id"]},
        ),
    ]
