# Generated by Django 5.2.7 on 2026-07-05 04:47

from django.db import migrations, models

import monitor.models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0014_alter_device_device_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="monitortarget",
            options={"ordering": ["host", "port", "id"]},
        ),
        migrations.RemoveField(
            model_name="device",
            name="api_password",
        ),
        migrations.RemoveField(
            model_name="device",
            name="api_port",
        ),
        migrations.RemoveField(
            model_name="device",
            name="api_username",
        ),
        migrations.AlterField(
            model_name="device",
            name="host",
            field=models.CharField(
                help_text="Endereço IP ou Hostname (ex: 172.31.255.2)",
                max_length=255,
                validators=[monitor.models.validate_host],
            ),
        ),
        migrations.AlterField(
            model_name="monitortarget",
            name="host",
            field=models.CharField(
                help_text="Endereço IP ou Hostname (ex: 10.0.0.1 ou google.com)",
                max_length=255,
                validators=[monitor.models.validate_host],
            ),
        ),
        migrations.AlterField(
            model_name="monitortarget",
            name="sensor_type",
            field=models.CharField(
                choices=[
                    ("tcp", "Porta TCP"),
                    ("ping", "Ping (ICMP)"),
                    ("snmp_traffic", "Tráfego SNMP"),
                    ("snmp_numeric", "Valor Numérico SNMP"),
                ],
                default="tcp",
                help_text="Tipo de monitoramento/coleta",
                max_length=50,
            ),
        ),
    ]
