# Generated by Django 6.0.6 on 2026-07-28 03:48

import django.db.models.deletion
from django.db import migrations, models

import monitor.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_company_customuser_company"),
        ("monitor", "0015_alter_monitortarget_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="devices",
                to="accounts.company",
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="groups",
                to="accounts.company",
            ),
        ),
        migrations.AddField(
            model_name="monitortarget",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="targets",
                to="accounts.company",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="changes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="model_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="object_repr",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="dailysummary",
            name="availability",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="dailysummary",
            name="avg_latency",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="device",
            name="check_interval",
            field=models.IntegerField(
                choices=[
                    (1, "A cada 1 minuto"),
                    (5, "A cada 5 minutos"),
                    (15, "A cada 15 minutos"),
                    (30, "A cada 30 minutos"),
                    (48, "A cada 48 minutos (30 vezes por dia)"),
                    (60, "A cada 1 hora"),
                    (120, "A cada 2 horas"),
                    (360, "A cada 6 horas"),
                    (720, "A cada 12 horas"),
                    (1440, "A cada 24 horas (1 vez por dia)"),
                ],
                default=60,
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="device_type",
            field=models.CharField(
                choices=[
                    ("mikrotik_snmp", "MikroTik (SNMP)"),
                    ("parks_olt", "OLT Parks GPON"),
                    ("generic_snmp", "Genérico (SNMP)"),
                    ("generic_ping", "Genérico (Apenas Ping)"),
                ],
                default="mikrotik_snmp",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="devices",
                to="monitor.group",
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="host",
            field=models.CharField(
                max_length=255, validators=[monitor.models.validators.validate_host]
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="device",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="device",
            name="snmp_community",
            field=models.CharField(default="public", max_length=255),
        ),
        migrations.AlterField(
            model_name="device",
            name="snmp_port",
            field=models.IntegerField(default=161),
        ),
        migrations.AlterField(
            model_name="device",
            name="telegram_alert_threshold",
            field=models.IntegerField(
                choices=[
                    (1, "Imediatamente (1ª falha)"),
                    (2, "Após 2 falhas consecutivas"),
                    (3, "Após 3 falhas consecutivas"),
                    (0, "Desativar Alertas (Não notificar)"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="monitorlog",
            name="latency",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="monitorlog",
            name="metric_value",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="monitorlog",
            name="status",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="monitortarget",
            name="check_interval",
            field=models.IntegerField(
                choices=[
                    (1, "A cada 1 minuto"),
                    (5, "A cada 5 minutos"),
                    (15, "A cada 15 minutos"),
                    (30, "A cada 30 minutos"),
                    (48, "A cada 48 minutos (30 vezes por dia)"),
                    (60, "A cada 1 hora"),
                    (120, "A cada 2 horas"),
                    (360, "A cada 6 horas"),
                    (720, "A cada 12 horas"),
                    (1440, "A cada 24 horas (1 vez por dia)"),
                ],
                default=60,
            ),
        ),
        migrations.AlterField(
            model_name="monitortarget",
            name="device",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sensors",
                to="monitor.device",
            ),
        ),
        migrations.AlterField(
            model_name="monitortarget",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="targets",
                to="monitor.group",
            ),
        ),
        migrations.AlterField(
            model_name="monitortarget",
            name="host",
            field=models.CharField(
                max_length=255, validators=[monitor.models.validators.validate_host]
            ),
        ),
        migrations.AlterField(
            model_name="monitortarget",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="monitortarget",
            name="label",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="monitortarget",
            name="last_counter_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="monitortarget",
            name="last_counter_val",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="monitortarget",
            name="last_latency",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="monitortarget",
            name="last_status",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="monitortarget",
            name="port",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="monitortarget",
            name="sensor_identifier",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="monitortarget",
            name="sensor_type",
            field=models.CharField(
                choices=[
                    ("tcp", "Porta TCP"),
                    ("ping", "Ping (ICMP)"),
                    ("snmp_traffic", "Tráfego SNMP"),
                    ("snmp_numeric", "Valor Numérico SNMP"),
                ],
                default="tcp",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="monitortarget",
            name="sensor_value",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="monitortarget",
            name="telegram_alert_threshold",
            field=models.IntegerField(
                choices=[
                    (1, "Imediatamente (1ª falha)"),
                    (2, "Após 2 falhas consecutivas"),
                    (3, "Após 3 falhas consecutivas"),
                    (0, "Desativar Alertas (Não notificar)"),
                ],
                default=1,
            ),
        ),
    ]
